name: CI / CD

on:
  push:
    branches: [ main, master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build CLine toolbox image
        run: |
          echo "Building CLine toolbox Docker image..."
          docker build -t cline-toolbox:latest -f Dockerfile.toolbox .
          docker images

      - name: Run build and deploy in container
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          ECR_REPOSITORY: ${{ secrets.ECR_REPOSITORY }}
          GITHUB_SHA: ${{ github.sha }}
        run: |
          echo "Running build_and_deploy.sh inside Docker container..."
          docker run --rm \
            -v "$(pwd):/app" \
            -w /app \
            -e AWS_ACCESS_KEY_ID \
            -e AWS_SECRET_ACCESS_KEY \
            -e AWS_REGION \
            -e ECR_REPOSITORY \
            -e GITHUB_SHA \
            cline-toolbox:latest \
            bash -c "chmod +x ./build_and_deploy.sh && ./build_and_deploy.sh"
