name: CI / CD

on:
  push:
    branches: [ main, master ]

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Debug Environment
        run: |
          echo "Current directory: $(pwd)"
          echo "Directory contents:"
          ls -la
          echo "System info:"
          uname -a
          echo "Available tools:"
          which bash curl wget jq
      
      - name: Install CLine CLI
        run: |
          echo "Installing CLine CLI..."
          curl -fsSL https://get.cline.dev -o install-cline.sh
          cat install-cline.sh
          bash install-cline.sh
          
          # Check installation result
          echo "CLine install location:"
          ls -la $HOME/.cline/bin || echo "CLine bin directory not found"
          
          # Add to PATH and verify
          export PATH="$PATH:$HOME/.cline/bin"
          echo "PATH is now: $PATH"
          
          # Check if cline is available
          which cline || echo "cline not found in PATH"
          
          # Try running cline directly with full path
          $HOME/.cline/bin/cline --version || echo "Could not run cline directly"
      
      - name: Setup CLine and tools
        run: |
          # Ensure PATH contains CLine
          export PATH="$PATH:$HOME/.cline/bin"
          
          echo "Installing plugins..."
          $HOME/.cline/bin/cline install tool-build || echo "Failed to install tool-build"
          
          echo "Making script executable..."
          chmod +x ./build_and_deploy.sh
          ls -la ./build_and_deploy.sh
          
          echo "Contents of build_and_deploy.sh:"
          cat ./build_and_deploy.sh
      
      - name: Simplified build and deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Direct execution of the build script
          echo "Running build script directly..."
          bash ./build_and_deploy.sh || echo "Script execution failed with exit code $?"
